language: ruby
rvm:
  - 2.2.4
cache: bundler
sudo: false
before_script:
  - cp .env.travis .env.test
  - psql -c 'create database travis_ci_test;' -U postgres
  - bin/setup
script:
  - bundle exec rspec spec
addons:
  postgresql: '9.4'
